import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className="text-3xl font-bold text-red-400">
      <Head>
        <title>Pomodoro</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h3>Hello World</h3>


    </div>
  )
}

export default Home
